
use unistam;
SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS=1;
DELIMITER  //

CREATE FUNCTION INCOMELEVEL (MONTHLY_VALUE INT)
RETURNS VARCHAR(20)
BEGIN 
   DECLARE INCOME_LEVEL VARCHAR(20);
   
   CASE MONTHLY_VALUE
      WHEN 4000 THEN
        SET INCOME_LEVEL='LOW INCOME';
    
      WHEN 5000 THEN
         SET INCOME_LEVEL ='AVG INCOME';

	  ELSE 
         SET INCOME_LEVEL ='AVG INCOME';
   END CASE;  
   RETURN INCOME_LEVEL;

END;//
select incomelevel(5300);
