CREATE DATABASE SALES;
use sales;
CREATE TABLE EMPLOYEE (EMP_ID INT(10),FIRST_Name char(20),last_name char(20),device_serial varchar(20),salary int(10));
INSERT INTO EMPLOYEE VALUES('1','RAM','SETHU','ACE123','34500'),('2','SAM','SEER','AWE129','35500'),('3','TEJ','SHARAM','KLE234','44500'),('4','KAREENA','KAPOOR','FCE456','66500'),('5','SHYAM','SETHU','ACE123','77500');
select*from EMPLOYEE;
DESC EMPLOYEE;
CREATE VIEW V1 as select EMP_ID,salary from employee;
desc v1;
insert into v1 values(101,10001);
select *from v1;
select*from employee;
delete from v1 where EMP_ID=10;
SET SQL_SAFE_UPDATES=0;
SELECT*FROM V1;
SELECT * FROM EMPLOYEE;
SELECT FIRST_name from employee where salary>45000;
create index index1 on employee(salary);
explain select first_name from employee where salary >45000;
drop index index1 on employee;
select first_name from employee where emp_id=4;
create index index1 on employee(emp_id);
explain select first_name from employee where emp_id=4;
 index1 from employee;