CREATE DATABASE HIGH;
USE HIGH;
CREATE TABLE CLSS(NAME CHAR(20),ID INT(10));
INSERT INTO CLSS VALUES('DJ',5);
COMMIT;
SET SQL_SAFE_UPDATES=0;
UPDATE CLSS SET NAME='BRAVO' WHERE ID='7';

SAVEPOINT A;
INSERT INTO CLSS VALUES('UPPL',8);
SAVEPOINT B;
INSERT INTO CLSS VALUES('BALU',7);
SAVEPOINT C;
SELECT*FROM CLSS;
rollback to B;
ROLLBACK TO A;

